# Generated by Django 4.0.3 on 2022-03-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memosource',
            old_name='meta',
            new_name='memo',
        ),
    ]
