# Generated by Django 4.0.3 on 2022-03-06 07:18

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_meta_memosource_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoitem',
            name='raw',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
