# Generated by Django 4.0.3 on 2022-03-06 09:01

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_memoitem_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='memomedia',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.memoitem'),
        ),
        migrations.AddField(
            model_name='memomedia',
            name='raw',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
