# Generated by Django 4.0.3 on 2022-03-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_memomedia_item_memomedia_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memomedia',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
